const char *MODEL_NAME                             = "Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz";
const unsigned int PHYSICAL_CHIPS                  = 2;
const unsigned int CORE_PER_CHIP                   = 1;
const unsigned int SMT_LEVEL                       = 1;
const unsigned int CACHE_PER_CORE                  = 4096;
const unsigned int seq_cores[]                     = {0,1};
const unsigned int rr_cores[]                      = {0,1};
const unsigned int test_hw_thr_cnts_fine_grain[]   = {1,2};
const unsigned int test_hw_thr_cnts_coarse_grain[] = {1,2};
